docs(usage): Update usage documentation
freeCodeCamp/cz-freecodecamp pull request #16
Opened 2017-07-03 06:17 UTC by raisedadead

Closes #15

2017-07-05 18:36 UTC, BerkeleyTrue commented
We should provide instructions for those who want to install it globally for all repose

2017-07-05 22:05 UTC, raisedadead commented
@BerkeleyTrue I have updated the instructions. Let me know if these are ok, thanks.

2017-07-05 22:16 UTC, BerkeleyTrue requested changes

2017-07-05 22:16 UTC, BerkeleyTrue commented on README.md
> +echo '{ "path": "cz-freecodecamp" }' > ~/.czrc
This won't work with global installs. The entire path of the global installs is needed.

For me it's `{ "path": "/usr/local/lib/node_modules/cz-conventional-changelog" }`
But this is going to be specific to the user. We need a way to programmatically get the users global npm install path

2017-07-05 23:13 UTC, erictleung commented on README.md
> +echo '{ "path": "cz-freecodecamp" }' > ~/.czrc
I haven't been able to test this locally yet, but according to their docs, that *should* work.

Source: https://github.com/commitizen/cz-cli#conventional-commit-messages-as-a-global-utility

2017-07-06 16:11 UTC, BerkeleyTrue approved these changes

2017-07-06 16:11 UTC, BerkeleyTrue commented on README.md
> +echo '{ "path": "cz-freecodecamp" }' > ~/.czrc
Ok, it works! It didn't work for me before. Thanks @erictleung

2017-07-06 16:11 UTC, merged

2017-07-06 17:44 UTC, raisedadead commented
Great that this worked out! Thanks for the QA.